# Generated by Django 3.2.4 on 2021-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ex_exercise_master',
            fields=[
                ('ex_em_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_shortname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=700)),
                ('video_path', models.CharField(max_length=700)),
                ('difficulty_level', models.IntegerField()),
                ('age_group', models.IntegerField(blank=True)),
                ('assistance', models.CharField(blank=True, max_length=300)),
                ('aim', models.CharField(blank=True, max_length=300)),
                ('instruction1', models.CharField(blank=True, max_length=1000)),
                ('instruction2', models.CharField(blank=True, max_length=1000)),
                ('status', models.IntegerField()),
                ('flex_field_1', models.CharField(blank=True, max_length=200)),
                ('flex_field_2', models.CharField(blank=True, max_length=200)),
                ('flex_field_3', models.CharField(blank=True, max_length=200)),
                ('flex_field_4', models.CharField(blank=True, max_length=200)),
                ('flex_field_5', models.CharField(blank=True, max_length=200)),
                ('search_tags', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ex_exercise_master',
            },
        ),
    ]
