# Generated by Django 3.2.4 on 2021-06-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='age_group',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='aim',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='assistance',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='difficulty_level',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='flex_field_1',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='flex_field_2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='flex_field_3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='flex_field_4',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='flex_field_5',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='image_path',
            field=models.CharField(default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='instruction1',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='search_tags',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='video_path',
            field=models.CharField(default=None, max_length=700, null=True),
        ),
    ]
