# Generated by Django 3.2.4 on 2021-06-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20210615_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_joint_master',
            fields=[
                ('ex_jm_id', models.AutoField(primary_key=True, serialize=False)),
                ('joint_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('model_name', models.CharField(max_length=200)),
                ('flex_field_1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('flex_field_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('flex_field_3', models.IntegerField(blank=True, default=None, null=True)),
                ('flex_field_4', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ex_movement_master',
            fields=[
                ('ex_mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('moment_direction', models.CharField(max_length=300)),
                ('pp_plan_id', models.IntegerField()),
                ('flex_field_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('flex_field_3', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ex_muscles_master',
            fields=[
                ('ex_mus_id', models.AutoField(primary_key=True, serialize=False)),
                ('muscle_name', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('flex_field_1', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('flex_field_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('flex_field_3', models.IntegerField(blank=True, default=None, null=True)),
                ('flex_field_4', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='image_path',
            field=models.CharField(blank=True, default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='ex_exercise_master',
            name='video_path',
            field=models.CharField(blank=True, default=None, max_length=700, null=True),
        ),
        migrations.CreateModel(
            name='Ex_ExerciseTemplates_master',
            fields=[
                ('ex_extmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_desc', models.CharField(max_length=1000)),
                ('sets', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.IntegerField(blank=True, default=None, null=True)),
                ('flex_field_1', models.CharField(max_length=200)),
                ('flex_field_2', models.CharField(max_length=200)),
                ('ex_em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_exercise_master')),
            ],
            options={
                'db_table': 'Ex_ExerciseTemplates_master',
            },
        ),
        migrations.CreateModel(
            name='ex_exercise_instructions',
            fields=[
                ('ex_ei_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=500)),
                ('ex_em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_exercise_master')),
            ],
            options={
                'db_table': 'ex_exercise_instructions',
            },
        ),
        migrations.CreateModel(
            name='ex_excercise_muscle_mapping',
            fields=[
                ('ex_exmus_id', models.AutoField(primary_key=True, serialize=False)),
                ('ex_plane_id', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.IntegerField()),
                ('flex_field_1', models.IntegerField(blank=True, default=None, null=True)),
                ('flex_field_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ex_em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_exercise_master')),
                ('ex_mus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_muscles_master')),
            ],
        ),
        migrations.CreateModel(
            name='ex_excercise_movement_mapping',
            fields=[
                ('ex_emm_id', models.AutoField(primary_key=True, serialize=False)),
                ('ex_plane_id', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.IntegerField()),
                ('flex_field_1', models.IntegerField(blank=True, default=None, null=True)),
                ('flex_field_2', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ex_em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_exercise_master')),
                ('ex_mov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_movement_master')),
            ],
        ),
        migrations.CreateModel(
            name='ex_excercise_joints_mapping',
            fields=[
                ('ex_ejm_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_angle', models.IntegerField()),
                ('min_angle', models.IntegerField()),
                ('joint_priority', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.IntegerField()),
                ('flex_field_1', models.IntegerField(blank=True, default=None, max_length=200, null=True)),
                ('flex_field_2', models.IntegerField(blank=True, default=None, null=True)),
                ('flex_field_3', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ex_em_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_exercise_master')),
                ('ex_jm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_joint_master')),
            ],
        ),
    ]
