# Generated by Django 3.2.4 on 2021-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20210616_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex_excercise_joints_mapping',
            name='flex_field_1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
