# Generated by Django 3.2.4 on 2021-06-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_ex_care_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='jointIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.ex_joint_master')),
            ],
        ),
    ]
