# Generated by Django 3.2.4 on 2021-07-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_jointindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex_care_plan',
            name='patient_details',
        ),
        migrations.AddField(
            model_name='ex_care_plan',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ex_care_plan',
            name='episode_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ex_care_plan',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ex_care_plan',
            name='time_slot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jointindex',
            name='joint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='exercise.ex_joint_master'),
        ),
    ]
