# Generated by Django 3.2.4 on 2021-07-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_pp_patient_master_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pp_patient_master',
            name='patient_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
