# Generated by Django 3.2.4 on 2021-07-10 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('patient', '0006_pp_patient_master_patient_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='pp_physiotherapist_master',
            fields=[
                ('pp_pm_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Auth.user')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Doctor_type', models.IntegerField()),
                ('Address_1', models.CharField(max_length=150)),
                ('Address_2', models.CharField(blank=True, max_length=150)),
                ('Address_3', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('whatsapp_no', models.CharField(max_length=12)),
                ('landline', models.CharField(max_length=12)),
                ('facebook', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('regd_no_1', models.CharField(max_length=50, unique=True)),
                ('regd_no_2', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('degree', models.CharField(max_length=12)),
                ('expertise_1', models.CharField(max_length=50)),
                ('expertise_2', models.CharField(blank=True, max_length=50)),
                ('expertise_3', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True)),
                ('status_flag', models.IntegerField()),
                ('roleId', models.IntegerField()),
            ],
            options={
                'db_table': 'pp_physiotherapist_master',
            },
        ),
    ]
